object Versions {
    const val ACTIVITY_KTX = "1.0.0"
    const val GRADLE_ANDROID = "4.1.1"
    const val KOTLIN = "1.3.72"
    const val KTX_CORE = "1.3.2"
    const val APPCOMPAT = "1.2.0"
    const val GOOGLE_MATERIAL_LIB = "1.2.1"
    const val FRAGMENT_KTX = "1.2.4"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val RETROFIT = "2.6.0"
    const val OKHTTP = "4.9.0"
    const val COROUTINES = "1.3.9"
    const val NETWORK_RESPONSE_ADAPTER = "4.0.1"
    const val HILT = "2.28-alpha"
    const val HILT_JETPACK = "1.0.0-alpha01"
    const val ROOM = "2.2.6"
    const val MOSHI = "1.9.3"
    const val LIFECYCLE = "2.2.0"
    const val GLIDE = "4.9.0"
    const val NAVIGATION = "2.2.2"
    const val SWIPE_REFRESH = "1.1.0"

    // test
    const val JUNIT = "4.+"
    const val JUNIT_ANDROID = "1.1.2"
    const val ESPRESSO = "3.3.0"
    const val RUNNER = "1.2.0"
    const val MOCKITO = "3.7.7"
}