name: Default-workflow
on: push
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      ## Initial setup.
      - name: Clone Codebase
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## run unit tests
      - name: Unit tests
        run: sudo bash ./gradlew test --stacktrace

  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      ## Initial setup.
      - name: Clone Codebase
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Generate debug/test apk
      - name: Generate debug build
        run: sudo ./gradlew --no-daemon -g /opt/gcache assembleDebug --stacktrace


      ## Upload debug apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk